---
- hosts: jenkins
  connection: local
  tasks:
    - name: Deploy Jar to Server 2
      shell: 'scp /var/jenkins_home/workspace/spring-petclinic/target/spring-petclinic-2.7.0-SNAPSHOT.jar jenkins@appserver: /home/jenkins/'
- hosts: appserver
  connection: ssh
  tasks:
    - name: Run jar
      shell: java -jar /home/jenkins/spring-petclinic-2.7.0-SNAPSHOT.jar
#- hosts: appserver
#  connection: ssh
#  tasks:
#    - name: Build an run service from image
#      docker_container:
#        name: pet-clinic-server
#        image: pet-clinic:latest
#        state: started
#        recreate: yes
#        detach: true
#        ports:
#          - "8888:8080"

